baseURL = 'https://thabet88.space'  # Thay báº±ng domain tháº­t cá»§a báº¡n
languageCode = 'vi'
title = 'Thabet88'
defaultContentLanguage = 'vi'

[build]
  writeStats = true

[params.auth]
  showButtons = true          # Hiá»‡n/áº©n buttons
  loginText = "ÄÄ‚NG NHáº¬P"     # Text button Ä‘Äƒng nháº­p  
  loginUrl = "/dang-nhap-thabet/" # Link Ä‘Äƒng nháº­p
  registerText = "ÄÄ‚NG KÃ"    # Text button Ä‘Äƒng kÃ½
  registerUrl = "/dang-ky-thabet/" # Link Ä‘Äƒng kÃ½
  loginStyle = "default"      # "default", "outline", "ghost"
  registerStyle = "default"   # "default", "outline", "ghost"
  buttonSize = "md"          # "sm", "md", "lg"
  mobileDisplay = "show"      # "show", "hide", "icons"
  loginTarget = "_self"       # "_self", "_blank"
  registerTarget = "_self"    # "_self", "_blank"

[taxonomies]
  category = 'categories'
  tag_display = "tag_displays"
  tag = 'tags'
  game_type = 'game_types'
  difficulty = 'difficulties'

[permalinks]
  tin-tuc = '/tin-tuc/:slug/'
  huong-dan = '/huong-dan/:slug/'
  tro-choi = '/tro-choi/:slug/'
  khuyen-mai = '/khuyen-mai/:slug/'
  tags = '/tag/:slug/'

# Category Pages Configuration
[params.categories]
  [params.categories.tin_tuc]
    title = "Tin Tá»©c Thabet"
    description = "Cáº­p nháº­t tin tá»©c má»›i nháº¥t vá» game, sá»± kiá»‡n vÃ  khuyáº¿n mÃ£i"
    icon = "ğŸ“°"
    color = "bg-blue-600"
    
  [params.categories.huong_dan]
    title = "HÆ°á»›ng Dáº«n Thabet88"
    description = "HÆ°á»›ng dáº«n chi tiáº¿t cÃ¡ch chÆ¡i game vÃ  sá»­ dá»¥ng dá»‹ch vá»¥"
    icon = "ğŸ“–"
    color = "bg-green-600"
    
  [params.categories.tro_choi]
    title = "TrÃ² ChÆ¡i"
    description = "KhÃ¡m phÃ¡ cÃ¡c trÃ² chÆ¡i háº¥p dáº«n táº¡i thabet"
    icon = "ğŸ®"
    color = "bg-purple-600"
    
  [params.categories.khuyen_mai]
    title = "Khuyáº¿n MÃ£i"
    description = "CÃ¡c chÆ°Æ¡ng trÃ¬nh khuyáº¿n mÃ£i háº¥p dáº«n"
    icon = "ğŸ"
    color = "bg-red-600"

[params]
  description = 'Cá»•ng game giáº£i trÃ­ hÃ ng Ä‘áº§u Viá»‡t Nam. KhÃ¡m phÃ¡ hÃ ng nghÃ¬n trÃ² chÆ¡i thÃº vá»‹ vÃ  káº¿t ná»‘i vá»›i cá»™ng Ä‘á»“ng game thá»§.'
  author = 'Cá»•ng game thabet'
  logo = '/images/thabet.webp'
  favicon = '/images/thabet-favicon.png'
  ogImage = '/images/thabet-og.webp'
  
  # Social Media
  facebook = 'https://facebook.com/thabet88space'
  twitter = 'https://twitter.com/thabet88space'
  youtube = 'https://youtube.com/@thabet88space'
  
  # Gaming specific
  totalGames = '1000+'
  totalPlayers = '500K+'
  totalPlays = '1M+'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Menu Configuration
[[menu.main]]
  name = "TRANG CHá»¦ THABET88"
  url = "https://thabet88.space"
  weight = 10
  pre = "ğŸ "

[[menu.main]]
  name = "TRÃ’ CHÆ I THABET88"
  url = "#"
  weight = 30
  pre = "ğŸ®"
  identifier = "tro-choi"

  [[menu.main]]
    parent = "tro-choi"
    name = "Xá»” Sá» THABET88"
    url = "/xo-so-thabet88/"
    weight = 31
    pre = "ğŸ²"

  [[menu.main]]
    parent = "tro-choi"
    name = "Báº®N CÃ THABET"
    url = "/ban-ca-thabet88/"
    weight = 32
    pre = "ğŸŸ"

  [[menu.main]]
    parent = "tro-choi"
    name = "THá»‚ THAO THABET88"
    url = "/the-thao-thabet88/"
    weight = 33
    pre = "âš½"

  [[menu.main]]
    parent = "tro-choi"
    name = "CASINO THABET88"
    url = "/casino-thabet88/"
    weight = 34
    pre = "ğŸ°"

  [[menu.main]]
    parent = "tro-choi"
    name = "GAME BÃ€I THABET88"
    url = "/game-bai-thabet88/"
    weight = 35
    pre = "ğŸƒ"

  [[menu.main]]
    parent = "tro-choi"
    name = "Ná»” HÅ¨ THABET88"
    url = "/no-hu-thabet88/"
    weight = 36
    pre = "ğŸ’¥"

[[menu.main]]
  name = "KHUYáº¾N MÃƒI"
  url = "/khuyen-mai/"
  weight = 40
  pre = "ğŸ"

[[menu.main]]
  name = "TIN Tá»¨C"
  url = "/tin-tuc/"
  weight = 50
  pre = "ğŸ“°"